# Generated by Django 4.2 on 2026-09-08 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_address_customuser_lat_customuser_lon'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('active', 'Активен'), ('ended', 'Завершен'), ('missed', 'Пропущен'), ('rejected', 'Отклонен')], default='pending', max_length=20, verbose_name='Статус')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Время начала')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('duration', models.IntegerField(default=0, verbose_name='Длительность (секунды)')),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_calls', to=settings.AUTH_USER_MODEL, verbose_name='Звонящий')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_calls', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Видео-звонок',
                'verbose_name_plural': 'Видео-звонки',
                'ordering': ('-created_at',),
            },
        ),
    ]
