# Generated by Django 4.2 on 2026-09-27 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_videocall'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoCall',
        ),
    ]
